export interface Product {
	id: number;
	name: string;
	price: string;
	image: string;
	description: string;
	vibe: string;
	details: string[];
}

export const products: Product[] = [
	// Elegant items
	{
		id: 1,
		name: "Elegant Gold Earrings",
		price: "₹12,999",
		image: "/elegant-gold-earrings-jewelry.jpg",
		description: "A handcrafted 22K gold earring inspired by celebrity fashion. These stunning earrings feature intricate detailing and a timeless design that complements any outfit. Perfect for special occasions or adding a touch of elegance to your everyday look.",
		vibe: "elegant",
		details: [
			"Material: 22K Gold",
			"Weight: 8.5 grams",
			"Design: Traditional with modern twist",
			"Occasion: Weddings, Parties, Festivals",
		],
	},
	{
		id: 2,
		name: "Elegant Pearl Necklace",
		price: "₹8,500",
		image: "/pearl-drop-earrings-luxury.jpg",
		description: "Refined pearl necklace with lustrous freshwater pearls. Each pearl is carefully selected for its perfect shape and brilliant shine. Ideal for formal events and sophisticated gatherings.",
		vibe: "elegant",
		details: [
			"Material: Freshwater Pearls, Sterling Silver",
			"Length: 18 inches",
			"Pearl Size: 8-10mm",
			"Occasion: Formal events, Business meetings",
		],
	},
	{
		id: 3,
		name: "Elegant Rose Gold Set",
		price: "₹28,000",
		image: "/royal-gold-bracelet-jewelry.jpg",
		description: "Sophisticated rose gold jewelry set featuring necklace, earrings, and bracelet. The warm rose gold tone adds a romantic touch to any ensemble.",
		vibe: "elegant",
		details: [
			"Material: 18K Rose Gold",
			"Set Includes: Necklace, Earrings, Bracelet",
			"Weight: 25 grams total",
			"Occasion: Weddings, Anniversary, Special celebrations",
		],
	},
	// Glamorous items
	{
		id: 4,
		name: "Diamond Necklace",
		price: "₹45,000",
		image: "/diamond-necklace-luxury-jewelry.jpg",
		description: "Stunning diamond necklace set with brilliant cut diamonds. This showstopper piece features exceptional clarity and sparkle that catches light from every angle.",
		vibe: "glamorous",
		details: [
			"Material: 18K White Gold, Natural Diamonds",
			"Total Carat Weight: 2.5 carats",
			"Diamond Quality: VS1-VS2, F-G Color",
			"Occasion: Red carpet events, Galas, Premium celebrations",
		],
	},
	{
		id: 5,
		name: "Glamorous Diamond Earrings",
		price: "₹32,000",
		image: "/elegant-gold-earrings-jewelry.jpg",
		description: "Sparkling diamond drop earrings that make a bold statement. These glamorous earrings feature cascading diamonds in an elegant drop design.",
		vibe: "glamorous",
		details: [
			"Material: Platinum, Natural Diamonds",
			"Total Carat Weight: 1.8 carats",
			"Length: 2.5 inches",
			"Occasion: Evening parties, Award ceremonies, Luxury events",
		],
	},
	{
		id: 6,
		name: "Glamorous Crystal Set",
		price: "₹38,500",
		image: "/diamond-necklace-luxury-jewelry.jpg",
		description: "Dazzling crystal jewelry collection with Swarovski crystals. This complete set radiates luxury and sophistication.",
		vibe: "glamorous",
		details: [
			"Material: Sterling Silver, Swarovski Crystals",
			"Set Includes: Necklace, Earrings, Ring, Bracelet",
			"Crystal Count: 150+ crystals",
			"Occasion: Theatre premieres, Fashion shows, High-end parties",
		],
	},
	// Traditional items
	{
		id: 7,
		name: "Royal Bracelet",
		price: "₹22,500",
		image: "/royal-gold-bracelet-jewelry.jpg",
		description: "Exquisite gold bracelet design inspired by royal heritage. Features traditional motifs and intricate craftsmanship passed down through generations.",
		vibe: "traditional",
		details: [
			"Material: 22K Gold",
			"Weight: 15 grams",
			"Design: Traditional royal motifs",
			"Occasion: Traditional ceremonies, Cultural festivals",
		],
	},
	{
		id: 8,
		name: "Traditional Gold Necklace",
		price: "₹35,000",
		image: "/diamond-necklace-luxury-jewelry.jpg",
		description: "Classic traditional gold necklace with heritage designs. This timeless piece represents cultural richness and traditional craftsmanship.",
		vibe: "traditional",
		details: [
			"Material: 22K Gold",
			"Weight: 28 grams",
			"Design: Heritage temple jewelry style",
			"Occasion: Weddings, Religious ceremonies, Cultural events",
		],
	},
	{
		id: 9,
		name: "Heritage Earrings",
		price: "₹15,000",
		image: "/elegant-gold-earrings-jewelry.jpg",
		description: "Traditional heritage design earrings that embody the essence of Indian culture. These earrings are perfect for adding a touch of tradition to any outfit.",
		vibe: "traditional",
		details: [
			"Material: 22K Gold",
			"Weight: 10 grams",
			"Design: Antique heritage style",
			"Occasion: Cultural festivals, Traditional weddings",
		],
	},
	{
		id: 10,
		name: "Traditional Bangles Set",
		price: "₹18,500",
		image: "/royal-gold-bracelet-jewelry.jpg",
		description: "Classic gold bangles collection featuring intricate designs. These bangles are a symbol of tradition and are often worn during auspicious occasions.",
		vibe: "traditional",
		details: [
			"Material: 22K Gold",
			"Weight: 20 grams",
			"Design: Intricate traditional patterns",
			"Occasion: Weddings, Festivals, Traditional ceremonies",
		],
	},
	// Classic items
	{
		id: 11,
		name: "Pearl Drop Earrings",
		price: "₹18,999",
		image: "/pearl-drop-earrings-luxury.jpg",
		description: "Classic pearl elegance earrings that are a must-have in every jewelry collection. These earrings feature high-quality pearls with a beautiful luster.",
		vibe: "classic",
		details: [
			"Material: Freshwater Pearls, 14K Gold",
			"Weight: 7 grams",
			"Design: Timeless pearl drop",
			"Occasion: Formal events, Dinner parties, Weddings",
		],
	},
	{
		id: 12,
		name: "Classic Diamond Ring",
		price: "₹25,000",
		image: "/elegant-gold-earrings-jewelry.jpg",
		description: "Timeless diamond solitaire ring that exudes sophistication. This classic ring features a single diamond in a sleek setting, perfect for engagements or as a statement piece.",
		vibe: "classic",
		details: [
			"Material: 18K White Gold, Natural Diamond",
			"Carat Weight: 0.75 carats",
			"Diamond Quality: SI1, G-H Color",
			"Occasion: Engagements, Anniversaries, Special occasions",
		],
	},
	{
		id: 13,
		name: "Classic Pearl Bracelet",
		price: "₹12,500",
		image: "/pearl-drop-earrings-luxury.jpg",
		description: "Elegant pearl bracelet that adds a touch of class to any outfit. This bracelet is designed with high-quality pearls and a secure clasp.",
		vibe: "classic",
		details: [
			"Material: Freshwater Pearls, Sterling Silver",
			"Length: 7.5 inches",
			"Pearl Size: 6-8mm",
			"Occasion: Everyday wear, Office, Casual outings",
		],
	},
	// Minimal items
	{
		id: 14,
		name: "Minimalist Silver Ring",
		price: "₹8,999",
		image: "/elegant-gold-earrings-jewelry.jpg",
		description: "Simple and clean design silver ring that complements any outfit. This minimalist ring is perfect for those who prefer understated elegance.",
		vibe: "minimal",
		details: [
			"Material: Sterling Silver",
			"Weight: 5 grams",
			"Design: Sleek and modern",
			"Occasion: Daily wear, Office, Casual outings",
		],
	},
	{
		id: 15,
		name: "Minimal Gold Chain",
		price: "₹6,500",
		image: "/royal-gold-bracelet-jewelry.jpg",
		description: "Delicate gold chain necklace that adds a subtle shine to your neckline. This minimalist chain is perfect for layering or wearing alone.",
		vibe: "minimal",
		details: [
			"Material: 14K Gold",
			"Length: 18 inches",
			"Chain Type: Cable chain",
			"Occasion: Everyday wear, Office, Casual outings",
		],
	},
	{
		id: 16,
		name: "Minimal Stud Earrings",
		price: "₹4,800",
		image: "/pearl-drop-earrings-luxury.jpg",
		description: "Simple elegant studs that are a staple in every jewelry collection. These earrings are perfect for adding a touch of elegance to any look.",
		vibe: "minimal",
		details: [
			"Material: 14K Gold",
			"Weight: 3 grams",
			"Design: Classic round studs",
			"Occasion: Daily wear, Office, Casual outings",
		],
	},
	{
		id: 17,
		name: "Minimal Bracelet",
		price: "₹7,200",
		image: "/diamond-necklace-luxury-jewelry.jpg",
		description: "Clean line bracelet design that offers a modern and sophisticated look. This minimalist bracelet is perfect for any occasion.",
		vibe: "minimal",
		details: [
			"Material: Sterling Silver",
			"Weight: 10 grams",
			"Design: Geometric open cuff",
			"Occasion: Everyday wear, Office, Casual outings",
		],
	},
	// Bold items
	{
		id: 18,
		name: "Bold Statement Necklace",
		price: "₹35,000",
		image: "/diamond-necklace-luxury-jewelry.jpg",
		description: "Eye-catching bold design necklace that is sure to turn heads. This statement piece is perfect for adding a focal point to any outfit.",
		vibe: "bold",
		details: [
			"Material: 18K Gold, Natural Diamonds",
			"Total Carat Weight: 3.0 carats",
			"Diamond Quality: VS2-SI1, G-H Color",
			"Occasion: Fashion shows, High-end parties, Special events",
		],
	},
	{
		id: 19,
		name: "Bold Geometric Earrings",
		price: "₹15,500",
		image: "/elegant-gold-earrings-jewelry.jpg",
		description: "Statement geometric design earrings that add an artistic touch to your look. These earrings are perfect for the modern, fashion-forward individual.",
		vibe: "bold",
		details: [
			"Material: Sterling Silver, 18K Gold Plating",
			"Weight: 12 grams",
			"Design: Abstract geometric shapes",
			"Occasion: Art exhibitions, Fashion events, Parties",
		],
	},
	{
		id: 20,
		name: "Bold Chunky Bracelet",
		price: "₹22,000",
		image: "/royal-gold-bracelet-jewelry.jpg",
		description: "Bold chunky gold bracelet that makes a powerful statement. This bracelet is designed for those who love to stand out.",
		vibe: "bold",
		details: [
			"Material: 22K Gold",
			"Weight: 30 grams",
			"Design: Chunky link bracelet",
			"Occasion: Fashion events, Parties, Special occasions",
		],
	},
	// Modern items
	{
		id: 21,
		name: "Modern Geometric Earrings",
		price: "₹15,999",
		image: "/royal-gold-bracelet-jewelry.jpg",
		description: "Contemporary design earrings with a bold geometric pattern. These earrings are perfect for adding a modern touch to any outfit.",
		vibe: "modern",
		details: [
			"Material: Sterling Silver, 18K Gold Plating",
			"Weight: 10 grams",
			"Design: Geometric shapes with cut-out details",
			"Occasion: Modern art exhibitions, Fashion events, Parties",
		],
	},
	{
		id: 22,
		name: "Modern Silver Set",
		price: "₹19,500",
		image: "/diamond-necklace-luxury-jewelry.jpg",
		description: "Contemporary silver collection featuring a necklace, earrings, and bracelet. This set is perfect for the modern individual who loves sleek designs.",
		vibe: "modern",
		details: [
			"Material: Sterling Silver",
			"Set Includes: Necklace, Earrings, Bracelet",
			"Weight: 50 grams total",
			"Occasion: Office, Casual outings, Modern events",
		],
	},
	{
		id: 23,
		name: "Modern Wire Bracelet",
		price: "₹11,000",
		image: "/elegant-gold-earrings-jewelry.jpg",
		description: "Sleek modern wire design bracelet that offers a unique look. This bracelet is perfect for those who appreciate contemporary jewelry.",
		vibe: "modern",
		details: [
			"Material: Stainless Steel, 18K Gold Plating",
			"Weight: 15 grams",
			"Design: Wire wrapped cuff",
			"Occasion: Everyday wear, Office, Casual outings",
		],
	},
	// Romantic items
	{
		id: 24,
		name: "Romantic Rose Gold Bracelet",
		price: "₹25,000",
		image: "/pearl-drop-earrings-luxury.jpg",
		description: "Delicate and romantic rose gold bracelet that adds a touch of romance to any outfit. This bracelet is perfect for special occasions.",
		vibe: "romantic",
		details: [
			"Material: 18K Rose Gold",
			"Weight: 12 grams",
			"Design: Delicate chain with heart motifs",
			"Occasion: Romantic dinners, Anniversaries, Special occasions",
		],
	},
	{
		id: 25,
		name: "Romantic Heart Necklace",
		price: "₹14,500",
		image: "/diamond-necklace-luxury-jewelry.jpg",
		description: "Sweet heart pendant design necklace that symbolizes love and affection. This necklace is a perfect gift for loved ones.",
		vibe: "romantic",
		details: [
			"Material: 14K Gold, Natural Diamonds",
			"Weight: 8 grams",
			"Design: Heart-shaped pendant with diamond accent",
			"Occasion: Valentine's Day, Anniversaries, Romantic dinners",
		],
	},
	{
		id: 26,
		name: "Romantic Pearl Set",
		price: "₹32,000",
		image: "/royal-gold-bracelet-jewelry.jpg",
		description: "Romantic pearl collection featuring a necklace, earrings, and bracelet. This set is perfect for adding a touch of romance to any outfit.",
		vibe: "romantic",
		details: [
			"Material: Freshwater Pearls, 14K Gold",
			"Weight: 40 grams total",
			"Design: Classic pearl strand with gold accents",
			"Occasion: Weddings, Anniversaries, Special celebrations",
		],
	},
	// Edgy items
	{
		id: 27,
		name: "Edgy Chain Necklace",
		price: "₹18,500",
		image: "/elegant-gold-earrings-jewelry.jpg",
		description: "Rock-inspired design necklace featuring a bold chain pattern. This necklace is perfect for adding an edgy touch to any outfit.",
		vibe: "edgy",
		details: [
			"Material: Stainless Steel, Black Rhodium Plating",
			"Weight: 20 grams",
			"Design: Chunky chain links",
			"Occasion: Concerts, Night out, Fashion events",
		],
	},
	{
		id: 28,
		name: "Edgy Spike Earrings",
		price: "₹9,800",
		image: "/pearl-drop-earrings-luxury.jpg",
		description: "Bold spike design earrings that make a strong statement. These earrings are perfect for the edgy, fashion-forward individual.",
		vibe: "edgy",
		details: [
			"Material: Sterling Silver, Black Onyx",
			"Weight: 10 grams",
			"Design: Spike-shaped dangles",
			"Occasion: Rock concerts, Fashion events, Night out",
		],
	},
	// Sophisticated items
	{
		id: 29,
		name: "Sophisticated Pearl Set",
		price: "₹42,000",
		image: "/diamond-necklace-luxury-jewelry.jpg",
		description: "Refined and polished pearl set that exudes sophistication. This set is perfect for the discerning individual who appreciates fine jewelry.",
		vibe: "sophisticated",
		details: [
			"Material: South Sea Pearls, 18K Gold",
			"Weight: 35 grams total",
			"Design: Elegant pearl strand with gold clasp",
			"Occasion: Galas, High-end events, Special celebrations",
		],
	},
	{
		id: 30,
		name: "Sophisticated Diamond Bracelet",
		price: "₹38,000",
		image: "/royal-gold-bracelet-jewelry.jpg",
		description: "Elegant diamond tennis bracelet that adds a touch of luxury to any outfit. This bracelet is perfect for those who love sophisticated jewelry.",
		vibe: "sophisticated",
		details: [
			"Material: 18K White Gold, Natural Diamonds",
			"Total Carat Weight: 2.0 carats",
			"Diamond Quality: VS1-VS2, F-G Color",
			"Occasion: Black tie events, Galas, Special occasions",
		],
	},
];
